export const VISITOR_AUTH_ERROR = {
  VALIDATION_LOGIN_REQUIRED: "VALIDATION_LOGIN_REQUIRED",
  VALIDATION_SIGNUP_REQUIRED: "VALIDATION_SIGNUP_REQUIRED",
  INVALID_EMAIL_OR_PIN: "INVALID_EMAIL_OR_PIN",
  VISITOR_LOCKED: "VISITOR_LOCKED",
  SIGNUP_EMAIL_EXISTS: "SIGNUP_EMAIL_EXISTS",
  SIGNUP_INVALID_EMAIL: "SIGNUP_INVALID_EMAIL",
  SIGNUP_UNAVAILABLE: "SIGNUP_UNAVAILABLE",
  UNEXPECTED: "UNEXPECTED",
} as const

export type VisitorAuthErrorCode =
  (typeof VISITOR_AUTH_ERROR)[keyof typeof VISITOR_AUTH_ERROR]

const VISITOR_AUTH_ERROR_VALUES = new Set<string>(Object.values(VISITOR_AUTH_ERROR))

export const isVisitorAuthErrorCode = (
  value: string,
): value is VisitorAuthErrorCode => VISITOR_AUTH_ERROR_VALUES.has(value)
